### ISSUE TITLE
Websocket notification closure handle not get fitrts tokens

### ISSUE THREAD

**Issue by cristianorevil** [AlboCode/ccatphp-sdk#3]
I have noticed that the notification handler function for streaming messages not receive first tokens but start from second or third, so the message chain is incomplete (i stream the message via api to another apllication). 
The message received in response to $cCatClient->sendMessage othwerwise contains all tokens.

**Comment by AlboCode** [comment]
Hi! 
I didn't notice this behavior, probably because I'm working with an older version of the cat. I will try to replicate and let you know as soon as possible

**Comment by cristianorevil** [comment]
Thanks. The issue not always present but at least 50% of times (i have setup a log directly in notification handler function to get all messages received and first tokens multiple times are not present)

**Comment by AlboCode** [comment]
The issue was caused by a old version of LangChain installed by a plugin
